### PR TITLE
Static workflow definition without globals

### LINKED ISSUE #67: Make the workflow and step decorators not depend on the creation of a Hatchet instance
As it stands, the workflow and step decorators have to be defined using a Hatchet App instance:

workflow
https://github.com/hatchet-dev/hatchet-python/blob/e358266f17da07a28373766c48ca68885cccc804/hatchet_sdk/hatchet.py#L59

step

https://github.com/hatchet-dev/hatchet-python/blob/e358266f17da07a28373766c48ca68885cccc804/hatchet_sdk/hatchet.py#L82

As far as I can tell, the only place where the client attribute that is set on the workflow meta is actually used is here where it is actually just used to access the configuration namespace.
https://github.com/hatchet-dev/hatchet-python/blob/e358266f17da07a28373766c48ca68885cccc804/hatchet_sdk/workflow.py#L16

Since workflows have to be registered with the worker ANYWAY, I don't see why all the things that might need the client or additional configuration can't be handled at that point:

https://github.com/hatchet-dev/hatchet-python/blob/2b54d5454156555175ad8ab973e3761a984a092b/hatchet_sdk/worker.py#L500

It seems to me that it would be much cleaner if Workflows could be defined declarative apart from any dynamic configuration that is needed to actually talk to a particular hatchet instance.

one idea for how to pull this off is to make everything that is calculated eagerly in the __new__ of workflow meta, instead be calculated dynamically/lazily as part of the call to get_actions, here:

https://github.com/hatchet-dev/hatchet-python/blob/2b54d5454156555175ad8ab973e3761a984a092b/hatchet_sdk/worker.py#L514

### PR DESCRIPTION
**Pull request by colonelpanic8**
Fixes #67

Open to suggestions about other ways to do this, but this seems like a pretty clean way to handle things.

### CODE REVIEW

**Comment by grutt** [comment]
Hi @colonelpanic8 I'll be taking a look at this change today. Thank you for opening this PR!

**Review by grutt — COMMENTED** [review]
@colonelpanic8 thank you for a quality PR. I think you took a sensible approach to this refactor and I was able to to verify everything runs as expected with our examples.

I'm going to have a quick chat with @abelanger5 later this morning to sanity check that this approach fits into some planned sdk changes we have in mind, should have an update or a merge later today.

**Comment by colonelpanic8** [comment]
> @colonelpanic8 thank you for a quality PR. I think you took a sensible approach to this refactor and I was able to to verify everything runs as expected with our examples.
> 
> I'm going to have a quick chat with @abelanger5 later this morning to sanity check that this approach fits into some planned sdk changes we have in mind, should have an update or a merge later today.

Awesome, thanks!

**Comment by colonelpanic8** [comment]
@grutt I merged with main here

**Review by grutt — APPROVED** [review]

**Comment by grutt** [comment]
@colonelpanic8 cleaned up a few things here and will have this included in `0.28.1` shortly.

**Pull request merged**
